# Generated by Django 6.0.7 on 2026-07-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(blank=True, help_text='Palabra clave de búsqueda para noticias macro/sectoriales sin ticker.', max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('url', models.TextField(blank=True)),
                ('url_hash', models.CharField(max_length=64, unique=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sentiment', models.FloatField(default=0.0, help_text='Compound VADER en [-1, 1].')),
                ('sentiment_label', models.CharField(choices=[('positive', 'Positivo'), ('neutral', 'Neutral'), ('negative', 'Negativo')], default='neutral', max_length=10)),
                ('impact_score', models.FloatField(default=0.0, help_text='Impacto estimado 0-100.')),
                ('category', models.CharField(choices=[('earnings', 'Resultados financieros'), ('products', 'Nuevos productos'), ('regulation', 'Regulación'), ('legal', 'Demandas / investigaciones'), ('mna', 'Fusiones y adquisiciones'), ('management', 'Cambios de directiva'), ('contracts', 'Contratos importantes'), ('geopolitics', 'Riesgo geopolítico'), ('technology', 'Innovación tecnológica'), ('other', 'Otros')], default='other', max_length=20)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='market.asset')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_items', to='core.evidencesource')),
            ],
            options={
                'verbose_name_plural': 'news',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['asset', '-published_at'], name='news_news_asset_i_52f85c_idx'), models.Index(fields=['category'], name='news_news_categor_05ff13_idx')],
            },
        ),
    ]
