# Generated by Django 6.0.7 on 2026-07-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('source_name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('official_filing', 'Reporte oficial / filing (SEC, IR)'), ('regulator', 'Regulador / banco central / organismo'), ('institutional', 'Banco de inversión / proveedor institucional'), ('financial_media', 'Medio financiero reconocido'), ('independent_analyst', 'Analista independiente verificable'), ('social', 'Redes sociales / foros'), ('promotional', 'Fuente anónima o promocional')], default='financial_media', max_length=30)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('relevant_excerpt', models.TextField(blank=True)),
                ('author_credentials', models.FloatField(default=50.0)),
                ('track_record', models.FloatField(default=50.0)),
                ('methodological_transparency', models.FloatField(default=50.0)),
                ('independence', models.FloatField(default=50.0)),
                ('reliability_score', models.FloatField(default=0.0)),
                ('reliability_level', models.CharField(default='E', max_length=2)),
                ('related_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_sources', to='market.asset')),
            ],
            options={
                'ordering': ['-retrieved_at'],
            },
        ),
    ]
