# Generated by Django 6.0.7 on 2026-07-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.CharField(default='sma_cross', max_length=50)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('initial_capital', models.FloatField(default=10000.0)),
                ('final_value', models.FloatField(null=True)),
                ('total_return_pct', models.FloatField(null=True)),
                ('cagr_pct', models.FloatField(null=True)),
                ('volatility_pct', models.FloatField(null=True)),
                ('max_drawdown_pct', models.FloatField(null=True)),
                ('win_rate_pct', models.FloatField(null=True)),
                ('sharpe_ratio', models.FloatField(null=True)),
                ('profit_factor', models.FloatField(null=True)),
                ('num_trades', models.IntegerField(default=0)),
                ('equity_curve', models.JSONField(blank=True, default=list)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='market.asset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario_name', models.CharField(default='escenario base', max_length=100)),
                ('initial_capital', models.FloatField()),
                ('monthly_contribution', models.FloatField(default=0.0)),
                ('time_horizon_years', models.FloatField()),
                ('expected_return', models.FloatField(help_text='Retorno anual esperado, ej. 0.08')),
                ('volatility', models.FloatField(help_text='Volatilidad anual esperada, ej. 0.15')),
                ('final_estimated_value', models.FloatField(null=True)),
                ('optimistic_value', models.FloatField(null=True)),
                ('pessimistic_value', models.FloatField(null=True)),
                ('total_contributed', models.FloatField(null=True)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulations', to='market.asset')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulations', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
