# Generated by Django 6.0.7 on 2026-07-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRiskMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_of', models.DateTimeField()),
                ('lookback_days', models.IntegerField(default=365)),
                ('volatility_annual', models.FloatField(help_text='Fracción, ej. 0.25', null=True)),
                ('max_drawdown', models.FloatField(help_text='Fracción negativa, ej. -0.35', null=True)),
                ('beta', models.FloatField(help_text='Beta vs benchmark (SPY)', null=True)),
                ('benchmark', models.CharField(default='SPY', max_length=20)),
                ('correlations', models.JSONField(blank=True, default=dict)),
                ('risk_score', models.FloatField(null=True)),
                ('notes', models.JSONField(blank=True, default=list)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_metrics', to='market.asset')),
            ],
            options={
                'verbose_name_plural': 'asset risk metrics',
                'ordering': ['-as_of'],
            },
        ),
    ]
