# Generated by Django 6.0.7 on 2026-07-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('asset_type', models.CharField(choices=[('stock', 'Acción'), ('index', 'Índice'), ('etf', 'ETF'), ('crypto', 'Criptomoneda'), ('bond', 'Bono / renta fija'), ('commodity', 'Commodity')], default='stock', max_length=20)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('exchange', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('high', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('low', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('close', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('volume', models.BigIntegerField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='market.asset')),
            ],
            options={
                'ordering': ['datetime'],
                'indexes': [models.Index(fields=['asset', '-datetime'], name='market_mark_asset_i_ac6c45_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'datetime'), name='uniq_price_asset_datetime')],
            },
        ),
        migrations.CreateModel(
            name='TechnicalIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_index=True)),
                ('sma_20', models.FloatField(null=True)),
                ('sma_50', models.FloatField(null=True)),
                ('sma_200', models.FloatField(null=True)),
                ('rsi', models.FloatField(null=True)),
                ('macd', models.FloatField(null=True)),
                ('macd_signal', models.FloatField(null=True)),
                ('macd_hist', models.FloatField(null=True)),
                ('bb_upper', models.FloatField(null=True)),
                ('bb_middle', models.FloatField(null=True)),
                ('bb_lower', models.FloatField(null=True)),
                ('volatility', models.FloatField(null=True)),
                ('relative_volume', models.FloatField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='market.asset')),
            ],
            options={
                'ordering': ['datetime'],
                'indexes': [models.Index(fields=['asset', '-datetime'], name='market_tech_asset_i_fef94b_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'datetime'), name='uniq_indicator_asset_datetime')],
            },
        ),
    ]
