# Generated by Django 6.0.7 on 2026-07-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundamentalRatios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_of', models.DateTimeField()),
                ('price_used', models.FloatField(null=True)),
                ('per', models.FloatField(null=True)),
                ('forward_per', models.FloatField(null=True)),
                ('peg', models.FloatField(null=True)),
                ('price_to_book', models.FloatField(null=True)),
                ('price_to_sales', models.FloatField(null=True)),
                ('dividend_yield', models.FloatField(help_text='Fracción, ej. 0.005 = 0.5%', null=True)),
                ('fcf_yield', models.FloatField(null=True)),
                ('enterprise_value', models.FloatField(null=True)),
                ('ev_ebitda', models.FloatField(null=True)),
                ('ev_ebit', models.FloatField(null=True)),
                ('ev_fcf', models.FloatField(null=True)),
                ('ev_sales', models.FloatField(null=True)),
                ('roe', models.FloatField(null=True)),
                ('roa', models.FloatField(null=True)),
                ('roic', models.FloatField(null=True)),
                ('gross_margin', models.FloatField(null=True)),
                ('operating_margin', models.FloatField(null=True)),
                ('net_margin', models.FloatField(null=True)),
                ('current_ratio', models.FloatField(null=True)),
                ('quick_ratio', models.FloatField(null=True)),
                ('net_debt_to_ebitda', models.FloatField(null=True)),
                ('interest_coverage', models.FloatField(null=True)),
                ('debt_to_equity', models.FloatField(help_text='Ratio, ej. 1.5', null=True)),
                ('wacc', models.FloatField(null=True)),
                ('dcf_fair_value', models.FloatField(null=True)),
                ('dcf_upside', models.FloatField(help_text='Fracción vs precio actual', null=True)),
                ('dcf_assumptions', models.JSONField(blank=True, default=dict, help_text='Supuestos explícitos del DCF (auditabilidad, sección 18).')),
                ('fundamental_score', models.FloatField(help_text='Score 0-100 para la capa mecánica (5.1).', null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundamental_ratios', to='market.asset')),
            ],
            options={
                'verbose_name_plural': 'fundamental ratios',
                'ordering': ['-as_of'],
            },
        ),
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statement_type', models.CharField(choices=[('income', 'Cuenta de resultados'), ('balance', 'Balance'), ('cashflow', 'Flujo de caja')], max_length=10)),
                ('period_ending', models.DateField()),
                ('data', models.JSONField(default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='market.asset')),
            ],
            options={
                'ordering': ['-period_ending'],
                'constraints': [models.UniqueConstraint(fields=('asset', 'statement_type', 'period_ending'), name='uniq_statement_asset_type_period')],
            },
        ),
    ]
