# Generated by Django 6.0.7 on 2026-07-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('firm', models.CharField(blank=True, max_length=200)),
                ('credentials', models.TextField(blank=True, help_text='CFA, CPA, etc.')),
                ('regulator_registry', models.CharField(blank=True, help_text='Ej. FINRA CRD# o registro SEC IAPD.', max_length=100)),
                ('registry_url', models.URLField(blank=True, max_length=500)),
                ('verified', models.BooleanField(default=False, help_text='Solo True tras verificar el registro regulatorio.')),
                ('verification_notes', models.TextField(blank=True)),
                ('disciplinary_history', models.TextField(blank=True)),
                ('methodology', models.TextField(blank=True)),
                ('conflicts_of_interest', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnalystConsensus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_of', models.DateTimeField()),
                ('source', models.CharField(default='yfinance', max_length=50)),
                ('strong_buy', models.IntegerField(default=0)),
                ('buy', models.IntegerField(default=0)),
                ('hold', models.IntegerField(default=0)),
                ('sell', models.IntegerField(default=0)),
                ('strong_sell', models.IntegerField(default=0)),
                ('total_analysts', models.IntegerField(default=0)),
                ('mean_target', models.FloatField(null=True)),
                ('high_target', models.FloatField(null=True)),
                ('low_target', models.FloatField(null=True)),
                ('median_target', models.FloatField(null=True)),
                ('current_price', models.FloatField(null=True)),
                ('rating_mean', models.FloatField(help_text='1=compra fuerte … 5=venta fuerte.', null=True)),
                ('dispersion', models.FloatField(help_text='(objetivo máx − mín) / promedio; >0.5 = opiniones muy dispersas.', null=True)),
                ('change_alert', models.CharField(blank=True, max_length=300)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consensus_snapshots', to='market.asset')),
            ],
            options={
                'verbose_name_plural': 'analyst consensus',
                'ordering': ['-as_of'],
            },
        ),
    ]
