# Generated by Django 6.0.7 on 2026-07-09 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('base_currency', models.CharField(default='USD', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=24)),
                ('average_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('fees', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('purchased_at', models.DateField(blank=True, null=True)),
                ('target_weight', models.FloatField(blank=True, help_text='Peso objetivo %% para rebalanceo (sección 4.9).', null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('profit_loss_pct', models.FloatField(blank=True, null=True)),
                ('last_valued_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='market.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['asset__ticker'],
            },
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_portfolio_user_name'),
        ),
        migrations.AddConstraint(
            model_name='portfolioposition',
            constraint=models.UniqueConstraint(fields=('portfolio', 'asset'), name='uniq_position_portfolio_asset'),
        ),
    ]
