# Generated by Django 6.0.7 on 2026-07-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mechanical_score', models.FloatField()),
                ('agent_score', models.FloatField()),
                ('confidence', models.FloatField(help_text='0-100')),
                ('signal', models.CharField(choices=[('strong_buy', 'Compra fuerte'), ('moderate_buy', 'Compra moderada'), ('hold', 'Mantener / observar'), ('high_risk', 'Riesgo alto'), ('avoid', 'Evitar / venta')], max_length=20)),
                ('justification', models.TextField()),
                ('contradictions_detected', models.JSONField(blank=True, default=list)),
                ('model_used', models.CharField(max_length=100)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_reviews', to='market.asset')),
                ('evidence_sources', models.ManyToManyField(blank=True, related_name='agent_reviews', to='core.evidencesource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal', models.CharField(choices=[('strong_buy', 'Compra fuerte'), ('moderate_buy', 'Compra moderada'), ('hold', 'Mantener / observar'), ('high_risk', 'Riesgo alto'), ('avoid', 'Evitar / venta')], max_length=20)),
                ('score', models.FloatField()),
                ('technical_score', models.FloatField(null=True)),
                ('news_score', models.FloatField(null=True)),
                ('fundamental_score', models.FloatField(null=True)),
                ('risk_score', models.FloatField(null=True)),
                ('explanation', models.TextField()),
                ('risks', models.TextField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='market.asset')),
                ('evidence_sources', models.ManyToManyField(blank=True, related_name='recommendations', to='core.evidencesource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
