# Generated by Django 6.0.7 on 2026-07-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('query', models.CharField(help_text='Búsqueda avanzada, ej. "quantum computing" AND investment', max_length=300)),
                ('category', models.CharField(choices=[('sector', 'Sector emergente'), ('company', 'Empresa en crecimiento'), ('crypto', 'Criptoactivo / protocolo'), ('country', 'País / macro'), ('commodity', 'Commodity'), ('etf', 'ETF nuevo'), ('technology', 'Tecnología'), ('regulation', 'Cambio regulatorio')], default='sector', max_length=20)),
                ('default_horizon', models.CharField(default='3-5 años', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('mention_count', models.IntegerField(default=0)),
                ('previous_mention_count', models.IntegerField(default=0)),
                ('momentum', models.FloatField(default=0.0, help_text='Variación relativa de menciones')),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('opportunity_type', models.CharField(choices=[('sector', 'Sector emergente'), ('company', 'Empresa en crecimiento'), ('crypto', 'Criptoactivo / protocolo'), ('country', 'País / macro'), ('commodity', 'Commodity'), ('etf', 'ETF nuevo'), ('technology', 'Tecnología'), ('regulation', 'Cambio regulatorio')], default='sector', max_length=20)),
                ('thesis', models.TextField()),
                ('risks', models.TextField()),
                ('horizon', models.CharField(max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('very_high', 'Muy alto'), ('extreme', 'Extremo / especulativo')], default='high', max_length=20)),
                ('score', models.FloatField(help_text='Emerging Market Score 0-100 (sección 13)')),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('conclusion', models.TextField()),
                ('evidence', models.ManyToManyField(blank=True, related_name='opportunity_reports', to='core.evidencesource')),
                ('related_assets', models.ManyToManyField(blank=True, related_name='opportunity_reports', to='market.asset')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='discovery.emergingtopic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
